// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ETyUHpg_KYQZiRE9aUw_P0Y6RVI_uQY',
    appId: '1:293124488959:web:3b1cd95f0bad1ffa0fd6ca',
    messagingSenderId: '293124488959',
    projectId: 'crudtodo-abdb5',
    authDomain: 'crudtodo-abdb5.firebaseapp.com',
    storageBucket: 'crudtodo-abdb5.appspot.com',
    measurementId: 'G-15QBDG7N9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF-qB9cmAF0ZhzrUjlphpjmPrbgFzZZCA',
    appId: '1:293124488959:android:fb2926ca9aceb7050fd6ca',
    messagingSenderId: '293124488959',
    projectId: 'crudtodo-abdb5',
    storageBucket: 'crudtodo-abdb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtpAyu_tTgPzKWF1VYqAA1L2LmHFCJLJo',
    appId: '1:293124488959:ios:201d218252f45e1e0fd6ca',
    messagingSenderId: '293124488959',
    projectId: 'crudtodo-abdb5',
    storageBucket: 'crudtodo-abdb5.appspot.com',
    iosBundleId: 'com.example.todoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtpAyu_tTgPzKWF1VYqAA1L2LmHFCJLJo',
    appId: '1:293124488959:ios:b58f19dff39c6ba10fd6ca',
    messagingSenderId: '293124488959',
    projectId: 'crudtodo-abdb5',
    storageBucket: 'crudtodo-abdb5.appspot.com',
    iosBundleId: 'com.example.todoFlutter.RunnerTests',
  );
}
